#!/usr/bin/env bash
# This script prints To infinity and beyond indefinitely
#+ Adds a sleep 2 in between each iteration
#+ displays I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!" ' TERM

while :
do
    echo "To infinity and beyond"
    sleep 2
done
