#!/usr/bin/env bash
# This script displays "Best School" 10 times and prints
#+ "Hi" on the 9th iteration using a while loop

start=0

while [ $start -lt 10 ]
do
  if [ $start -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( start++ ))
done
