#!/usr/bin/env bash
# This script loops from 1 to 10 and displays
#+ "bad luck" for the 4th loop iteration
#+ "good luck" for the 8th loop iteration
#+ "Best School" for other iterations using the While loop

start=0

while [ $start -lt 10 ]
do
  if [ $start -eq 3 ]
  then
    echo "bad luck"
  elif [ $start -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( start++ ))
done
