#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and also prints a string
#+ displays 4 then "bad luck form China" on the 4th iteration
#+ displays 9 then "bad luck from Japan" on the 9th iteration
#+ displays 17 then "bad luck from Italy" on the 17th iteration
#+ using a While loop with a case statement block

start=1

while [ $start -le 20 ]
do
  echo "$start"
  case $start in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( start++ ))
done
