#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 44.211.31.72
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
